[package]
name = "ssec-core"
version = "0.5.0-rc.4"
edition = "2024"
description = "streaming implementation of the SSEC file format"
categories = [ "asynchronous", "encoding", "security" ]
authors = [ "James Connolly <me@j-conn.com>" ]
license = "MIT OR Apache-2.0"
repository = "https://github.com/james-conn/ssec-core"

include = [
	"/Cargo.toml",
	"/src/*.rs",
	"LICENSE-MIT",
	"LICENSE-APACHE"
]

[dependencies.argon2]
version = "0.5"
default-features = false
features = [ "alloc" ]

[dependencies]
futures-core = "0.3"
bytes = "1"
rand_core = "0.9"
ctr = "0.9"
hmac = "0.12"
sha3 = "0.10"
pin-project-lite = "0.2"
aes = "0.8"
thiserror = "2"
zeroize = "1"
constant_time_eq = "0.4"

[dev-dependencies.tokio]
version = "1"
features = [ "rt", "macros" ]

[dev-dependencies.rand]
version = "0.9"
default-features = false
features = [ "std_rng" ]

[dev-dependencies]
futures-util = "0.3"

# turns out running a key derivation function with no optimization is slow, who would have guessed?
[profile.test]
opt-level = 1
