name: "Cargo Test"
on: [ "push", "pull_request" ]
env:
  CARGO_TERM_COLOR: "always"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      QUICKCHECK_MAX_TESTS: 10000000
      QUICKCHECK_TESTS: 5000
      QUICKCHECK_MIN_TESTS_PASSED: 5000

    steps:
    - uses: actions/checkout@v6
    - run: rustup default 1.95
    - run: cargo test --verbose
