name: "Cargo Test"
on: [ "push", "pull_request" ]
env:
  CARGO_TERM_COLOR: "always"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      QUICKCHECK_GENERATOR_SIZE: 50000
      QUICKCHECK_TESTS: 10000

    steps:
    - uses: actions/checkout@v4
    - run: cargo test --verbose
